### PR TITLE
add yfii 

### PR DESCRIPTION
**Pull request by jin10086**
yfii.finance

### CODE REVIEW

**Comment by penandlim** [comment]
This pull request is rejected until YFII key is burned or handed over to trust worthy multi sig address.

**Comment by jin10086** [comment]
@penandlim  https://burn.yfii.finance/  now YFII key is burned

**Comment by penandlim** [comment]
Minter access is still under question. Added the pages but left it out of other pages links and main page UI.

https://yieldfarming.info/yfii/ycrv/
https://yieldfarming.info/yfii/yfii_dai/

https://github.com/yieldfarming/yieldfarming/pull/13

**Comment by jin10086** [comment]
Mind Access only adds two contract addresses
0xb81D3cB2708530ea990a287142b82D058725C092
0xAFfcD3D45cEF58B1DfA773463824c6F6bB0Dc13a
No one can issue more shares at will

Check address: https://etherscan.io/txs?a=0x000000004fa9e635dBe91C83aEe357d01494936D&f=2

You can verify it yourself.

image

**Comment by penandlim** [comment]
Added to main UI https://github.com/yieldfarming/yieldfarming/commit/deb79d99a62b6a0862d7f4dabc276ede1623bf1a

**Comment by 8001800** [comment]
> @penandlim https://burn.yfii.finance/ now YFII key is burned

if it's burned, how can YFII be minted after 1st week  of 20k yffi distributed ?

**Comment by penandlim** [comment]
@8001800 YFII Owner and RewardDistribution access are burned to 0x000..000

The owner added 2 minters (the 2 reward contracts) before revoking himself. The minting activities are hard coded into the reward contracts.

**Pull request closed without merging**
